googleAnalytics = '' # TODO: create and set tracking id
baseURL = '/'
languageCode = 'en-us'
title = 'Advent of Emacs'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookLogo = 'logo.png'
BookTheme = 'light'
BookSearch = true

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[markup.tableOfContents]
  startLevel = 1