baseURL = '/'
languageCode = 'en-us'
title = 'Advent of Emacs'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookLogo = 'logo.png'
BookTheme = 'light'
BookSearch = false
